# Generated by Django 5.2.5 on 2025-09-30 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=100)),
                ('tipo_objetivo', models.CharField(max_length=7)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escaneo',
                'verbose_name_plural': 'Escaneos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='resultadoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(max_length=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('resultado', models.JSONField()),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('escaneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='scanner.escaneo')),
            ],
            options={
                'verbose_name': 'Resultado de Módulo',
                'verbose_name_plural': 'Resultados de Módulos',
                'ordering': ['escaneo', 'nombre_modulo'],
            },
        ),
    ]
