# Generated by Django 5.2.5 on 2025-11-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomodulo',
            name='analisis_ia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
